---
env:
  # PRE_GATE_SLEEP: "5"
  # START_GATE_SLEEP: "5"
  # DEPLOY_GATE_SLEEP: "5"
  # TEST_GATE_SLEEP: "5"
  # END_GATE_SLEEP: "5"
  # POST_GATE_SLEEP: "5"

steps:
  - label: ":orangutan: pre-gate"
    command: "echo \"before concurrency gate\"; sleep ${PRE_GATE_SLEEP}:-10}"
    key: pre-gate

  - label: ":llama: start-gate"
    command: "echo \"start of concurrency gate\"; sleep ${START_GATE_SLEEP:-10}"
    concurrency_group: gate
    concurrency: 1
    key: start-gate
    depends_on: pre-gate

  - wait

  - label: ":llama: deploy"
    command: "echo \"deploy (inside concurrency gate)\"; sleep ${DEPLOY_GATE_SLEEP:-10}"
    key: deploy
    depends_on: start-gate

  - label: ":llama: test"
    command: "echo \"test (inside concurrency gate)\"; sleep ${TEST_GATE_SLEEP:-10}"
    parallelism: 3
    depends_on: deploy
    key: test

  - wait

  - label: ":llama: end-gate"
    command: "echo \"end of concurrency gate\"; sleep ${END_GATE_SLEEP:-10}"
    concurrency_group: gate
    concurrency: 1
    key: end-gate

  - label: ":orangutan: post-gate"
    command: "echo \"after concurrency gate\"; sleep ${POST_GATE_SLEEP:-10}"
    depends_on: end-gate
