---
steps:
  - label: ":llama: pre-gate"
    command: "echo \"before concurrency gate\"; sleep ${PRE_GATE_SLEEP:-5}"
    key: pre-gate

  - label: ":unicorn_face: start-gate"
    command: "echo \"start of concurrency gate\"; sleep ${START_GATE_SLEEP:-5}"
    concurrency_group: gate
    concurrency: 1
    key: start-gate
    depends_on: pre-gate

  - wait

  - label: ":unicorn_face: deploy"
    command: "echo \"deploy (inside concurrency gate)\"; sleep ${DEPLOY_GATE_SLEEP:-5}"
    key: deploy-gate
    depends_on: start-gate

  - label: ":unicorn_face: test"
    command: "echo \"test (inside concurrency gate)\"; sleep ${TEST_GATE_SLEEP:-5}"
    parallelism: 3
    depends_on: deploy-gate
    key: test-gate

  - wait

  - label: ":unicorn_face: end-gate"
    command: "echo \"end of concurrency gate\"; sleep ${END_GATE_SLEEP:-5}"
    concurrency_group: gate
    concurrency: 1
    key: end-gate

  - label: ":llama: post-gate"
    command: "echo \"after concurrency gate\"; sleep ${POST_GATE_SLEEP:-5}"
    depends_on: end-gate

  - wait

  - label: ":butterfly: pre-group"
    command: "echo \"before concurrency group\"; sleep ${PRE_GROUP_SLEEP:-5}"
    key: pre-group

  - label: ":butterfly: start-group"
    command: "echo \"start of concurrency group\"; sleep ${START_GROUP_SLEEP:-5}"
    concurrency_group: group
    concurrency: 1
    key: start-group
    depends_on: pre-group

  - label: ":butterfly: deploy"
    command: "echo \"deploy (inside concurrency group)\"; sleep ${DEPLOY_GROUP_SLEEP:-5}"
    concurrency_group: group
    concurrency: 1
    key: deploy-group
    depends_on: start-group

  - label: ":butterfly: test"
    command: "echo \"test (inside concurrency group)\"; sleep ${TEST_GROUP_SLEEP:-5}"
    parallelism: 3
    concurrency_group: group
    concurrency: 1
    depends_on: deploy-group
    key: test-group
